/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author aluno
 */
public class main_view extends javax.swing.JFrame {

    /**
     * Creates new form main_view
     */
    public main_view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_principal = new javax.swing.JPanel();
        pitagoras = new javax.swing.JButton();
        gravidade = new javax.swing.JButton();
        relatividade = new javax.swing.JButton();
        caos = new javax.swing.JButton();
        clapeyron = new javax.swing.JButton();
        torricelli = new javax.swing.JButton();
        gauss = new javax.swing.JButton();
        particula = new javax.swing.JButton();
        main_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pitagoras.setText("Teorema de Pitágoras");
        pitagoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pitagorasActionPerformed(evt);
            }
        });

        gravidade.setText("Lei da Gravidade");
        gravidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravidadeActionPerformed(evt);
            }
        });

        relatividade.setText("Teoria da Relatividade");
        relatividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatividadeActionPerformed(evt);
            }
        });

        caos.setText("Teoria do Caos");
        caos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caosActionPerformed(evt);
            }
        });

        clapeyron.setText("Equação de Clapeyron");
        clapeyron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clapeyronActionPerformed(evt);
            }
        });

        torricelli.setText("Equalçao de Torricelli");
        torricelli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torricelliActionPerformed(evt);
            }
        });

        gauss.setText("Equação de Gauss");
        gauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaussActionPerformed(evt);
            }
        });

        particula.setText("Força sobre uma partícula");
        particula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                particulaActionPerformed(evt);
            }
        });

        main_text.setFont(new java.awt.Font("LM Sans 10", 0, 30)); // NOI18N
        main_text.setText("  Escolha uma das equações abaixo");
        main_text.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout painel_principalLayout = new javax.swing.GroupLayout(painel_principal);
        painel_principal.setLayout(painel_principalLayout);
        painel_principalLayout.setHorizontalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_principalLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(main_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painel_principalLayout.createSequentialGroup()
                        .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pitagoras, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gauss, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gravidade, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(relatividade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(clapeyron, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(torricelli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(particula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(118, 118, 118))
        );
        painel_principalLayout.setVerticalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_principalLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(main_text)
                .addGap(81, 81, 81)
                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_principalLayout.createSequentialGroup()
                        .addComponent(relatividade)
                        .addGap(18, 18, 18)
                        .addComponent(clapeyron)
                        .addGap(18, 18, 18)
                        .addComponent(torricelli)
                        .addGap(18, 18, 18)
                        .addComponent(particula))
                    .addGroup(painel_principalLayout.createSequentialGroup()
                        .addComponent(pitagoras)
                        .addGap(18, 18, 18)
                        .addComponent(caos)
                        .addGap(18, 18, 18)
                        .addComponent(gauss)
                        .addGap(18, 18, 18)
                        .addComponent(gravidade)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pitagorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pitagorasActionPerformed
        new pitagoras().setVisible(true); 
    }//GEN-LAST:event_pitagorasActionPerformed

    private void relatividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatividadeActionPerformed
        new relatividade().setVisible(true);
    }//GEN-LAST:event_relatividadeActionPerformed

    private void caosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caosActionPerformed
        new caos().setVisible(true);
    }//GEN-LAST:event_caosActionPerformed

    private void clapeyronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clapeyronActionPerformed
        new clapeyron().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_clapeyronActionPerformed

    private void gaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaussActionPerformed
        new gauss().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_gaussActionPerformed

    private void torricelliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torricelliActionPerformed
        new torricelli().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_torricelliActionPerformed

    private void gravidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravidadeActionPerformed
        new gravidade().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_gravidadeActionPerformed

    private void particulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_particulaActionPerformed
        new particula().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_particulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton caos;
    private javax.swing.JButton clapeyron;
    private javax.swing.JButton gauss;
    private javax.swing.JButton gravidade;
    private javax.swing.JLabel main_text;
    private javax.swing.JPanel painel_principal;
    private javax.swing.JButton particula;
    private javax.swing.JButton pitagoras;
    private javax.swing.JButton relatividade;
    private javax.swing.JButton torricelli;
    // End of variables declaration//GEN-END:variables
}
